[build]
  command = """
    corepack enable
    pnpm install --no-frozen-lockfile
    pnpm build
  """
  publish = "apps/web/build"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "8.15.6"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
