[build]
  command = """
    corepack enable
    pnpm install --no-frozen-lockfile
    cd apps/web
    pnpm exec svelte-kit sync
    cd ../..
    pnpm build
  """
  publish = ".svelte-kit/netlify"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "8.15.6"
  NODE_ENV = "production"

[functions]
  directory = ".svelte-kit/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/_app/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"
