[build]
  command = """
    npm i -g pnpm@8.15.6 typescript
    pnpm config set auto-install-peers true
    pnpm config set strict-peer-dependencies false
    pnpm install --no-frozen-lockfile
    pnpm build
  """
  publish = ".svelte-kit/netlify"
  
[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "8.15.6"
  NPM_FLAGS = "--no-audit --no-fund"
  
[functions]
  directory = ".svelte-kit/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/_app/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable" 