[build]
  command = "pnpm build"
  publish = ".svelte-kit/netlify"
  
[build.environment]
  NODE_VERSION = "18"
  
[functions]
  directory = ".svelte-kit/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/_app/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable" 