<script context="module">
	export const Icons = {
		logo: Sparkle,
		close: X,
		spinner: Loader2,
		chevronLeft: ChevronLeft,
		chevronRight: ChevronRight,
		trash: Trash,
		post: FileText,
		page: File,
		media: Image,
		copy: Clipboard,
		settings: Settings,
		billing: CreditCard,
		ellipsis: MoreVertical,
		add: Plus,
		warning: AlertTriangle,
		user: User,
		arrowRight: ArrowRight,
		help: HelpCircle,
		pizza: Pizza,
		sun: SunMedium,
		moon: Moon,
		laptop: Laptop,
		twitter: Twitter,
		check: Check,
		show: Eye,
		hide: EyeClosed,
		send: SendHorizonal,
		delete: Trash
	};
</script>

<script lang="ts">
	import {
		AlertTriangle,
		ArrowRight,
		Check,
		ChevronLeft,
		ChevronRight,
		Command,
		CreditCard,
		File,
		FileText,
		HelpCircle,
		Image,
		Laptop,
		PlusIcon,
		Loader2,
		Moon,
		MoreVertical,
		Pizza,
		Plus,
		Settings,
		Sparkle,
		SunMedium,
		Trash,
		Twitter,
		User,
		X,
		Eye,
		EyeClosed,
		type Icon as LucideIcon,
		SendHorizonal,
		Clipboard
	} from 'lucide-svelte';
</script>
